name: MSYS2 autotools build (Windows)

on:
  push:
    branches: [ master, test_ci ]
  pull_request:
    branches: [ master ]

env:
  # GitHub CI Actions-specific environment variables:

  # Location for user-local `make install`
  PORTAUDIO_INSTALL_DIR: ${HOME}/.local

  # Environment variables for compiling and running the test program.
  # Usually none of this is needed as `make install` would install to system locations
  # where include and library search paths are already set up to just work.
  # gcc environment variables. see https://gcc.gnu.org/onlinedocs/gcc/Environment-Variables.html
  C_INCLUDE_PATH: ${HOME}/.local/include
  LIBRARY_PATH: ${HOME}/.local/lib
  # LD_LIBRARY_PATH: ${HOME}/.local/lib
  # NOTE: msys2 doesn't use LD_LIBRARY_PATH. .dll files are installed in .local/bin
  # so add ./local/bin to PATH
  BIN_PATH: ${HOME}/.local/bin

jobs:
  msys2:
    name: msys2-${{ matrix.msystem }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - msystem: UCRT64
            pkg: mingw-w64-ucrt-x86_64-gcc
          - msystem: CLANGARM64
            pkg: mingw-w64-clang-aarch64-gcc
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: checkout PortAudio git repo
      uses: actions/checkout@v4

    - name: setup msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        # Install everything here to ensure a stable environment and avoid 'cygheap' errors
        install: >-
          git
          autoconf
          automake
          libtool
          autoconf-archive
          pkg-config
          make
          ${{ matrix.pkg }}

    - name: autoreconf
      run: autoreconf -fvi

    - name: configure
      run: ./configure --prefix=${{ env.PORTAUDIO_INSTALL_DIR }}

    - name: make
      run: make

    - name: install
      run: make install

    - name: build patest_init.c
      run: |
        # Use gcc directly; msys2 maps this to the correct compiler for the current MSYSTEM
        gcc -o patest_init.exe ./test/patest_init.c -I${{ env.C_INCLUDE_PATH }} -L${{ env.LIBRARY_PATH }} -lportaudio

    - name: run patest_init.exe
      run: |
        export PATH=${{ env.BIN_PATH }}:$PATH
        ./patest_init.exe

    - name: uninstall
      run: make uninstall

    - name: build patest_init.c to check uninstall (expect failure)
      run: |
        if gcc -o patest_init.exe ./test/patest_init.c -I${{ env.C_INCLUDE_PATH }} -L${{ env.LIBRARY_PATH }} -lportaudio; then 
          echo "Error: Build should have failed after uninstall"
          exit 1
        else 
          echo "Success: Build failed as expected"
          exit 0
        fi